#!/bin/bash

set -e

WALLET="0xc91B3f6a889a9963c7eaE2d5BD5Ca88a6Ae2d2EA";
WORKER="precision";
POOL="stratum+tcp://eu1.ethermine.org:4444";
POOL2="stratum+tcp://eu2.ethermine.org:4444";
POOL3="stratum+tcp://us1.ethermine.org:4444";
POOL4="stratum+tcp://pool.alpereum.ch:4001";
CUR="ETH";

if [[ "$1" == "ETC" ]]; then

WALLET="0x2699d8531BDE9606F257387fdf0EC7d498F6197c";
WORKER="precision";
POOL="stratum+tcp://eu1-etc.ethermine.org:4444";
POOL2="stratum+tcp://us1-etc.ethermine.org:4444";
POOL2="stratum+tcp://cn1-etc.ethermine.org:4444";
CUR="ETC";
fi

export GPU_FORCE_64BIT_PTR=1
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100

ARGS="-k ethash -w 256 -I 23 -g 1 -s 14 -E 42"

date "+%s" > /dev/shm/miner.start


#nice -n 10 ./sgminer-dev --protocol-dump --default-config=/dev/null --verbose --debug --load-balance -g1 -I20 -w256 -s7 -E28 -k ethash --queue 0 -p x -U "5;$POOL4" -O $WALLET.$WORKER:x --no-extranonce 2>/dev/shm/debug.log $1
nice -n 10 ./sgminer-dev --default-config=/dev/null --load-balance -g1 -I20 -w256 -s7 -E28 -k ethash --queue 0 -p x -U "5;$POOL4" -O $WALLET.$WORKER:x --no-extranonce 2>/dev/shm/debug.log $1

