#!/bin/bash

logto="null";

function l {
	t=`date "+%b %e %T"`;
	h=`hostname | cut -d "." -f 1`
	n="sgminer"
	echo "$t $h $n $1"
}

l "debug build started at `date`"

l "updating git submodules"
git submodule init
git submodule update
date "+%s" >/dev/shm/build.start
l "running autoreconf --install"
autoreconf -vi | tee /dev/$logto 1>build.log 2>build.err
l "running ./configure -ggdb -Wall -std=gnu99"

CFLAGS="-ggdb -march=native -std=gnu99 -I/opt/AMDPPSDK-3.0 -Wall" LDFLAGS="-L/opt/amdgpu-pro/lib/x86_64-linux-gnu/" \
  ./configure --prefix=/usr/local --disable-shared | tee /dev/$logto 1>>build.log 2>build.err

threads=$((`cat /proc/cpuinfo | grep processor | wc -l` + 1)); 
l "building sgminer using $threads compiler threads" 
make -j${threads} clean | tee /dev/$logto 1>>build.log 2>build.err 
make -j${threads} | tee /dev/$logto 1>build.log 2>build.err
if [[ -x "sgminer" ]]; then
  ver=$(./sgminer --version 2>/dev/null); 
  l "built executable: ./${ver}" | tee /dev/$logto
  rm -f build.err
else
  l "something wrong with the build. Here's the error log:"
  l ""
  cat build.err | tee /dev/$logto >>build.log
fi

elapsed=$((`date "+%s"` - `cat /dev/shm/build.start`))
l "debug build finished at `date` ($elapsed seconds)"
rm -f /dev/shm/build.start



